# Generated by Django 5.2.10 on 2026-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
                ('primary_color', models.CharField(max_length=20)),
            ],
        ),
    ]
